.
======================================================================
FAIL: test_splitting_messages (__main__.TestBufServer) [Client 2 should receive and correctly print first part of the split message from client 1]
Two clients connect to server and send messages to each other
----------------------------------------------------------------------
Traceback (most recent call last):
  File "clientserver_test.py", line 153, in test_splitting_messages
    self.assertIn(b'user1: ' + b'0123456789ABCDEF'*8 + b'\n', c2out)
AssertionError: b'user1: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF\n' not found in b'Please enter a username: user1: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDE\nuser1: 0123456789ABCDEF\n'

----------------------------------------------------------------------
Ran 2 tests in 1.362s

FAILED (failures=1)
