Autotested Results for A2 submitted by Ye Huang (huang853)
Generated at 2020-02-18T20:50:18

Summary of Results: 3 out of 6 tests successfully passed
--

Tests for create_tests.CreatefileTest (1/2 passed)
--

1) create_tests.CreatefileTest.test_nofentry                                          .. ok!
2) create_tests.CreatefileTest.test_emptyfs                                           .. failed
.. because False is not true (details below):

    Traceback (most recent call last):

      File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
        yield

      File "/usr/lib/python3.6/unittest/case.py", line 605, in run
        testMethod()

      File "/res/peters43/209/huang853/a2/test_helpers.py", line 243, in _t
        self.assertTrue(_diff_files(outputname, solname, start, len))

      File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
        raise self.failureException(msg)

    AssertionError: False is not true




Tests for read_tests.ReadfileTest (2/2 passed)
--

1) read_tests.ReadfileTest.test_firstfile_start0_lessthanblocksize                    .. ok!
2) read_tests.ReadfileTest.test_firstfile_start4_morethanblocksize                    .. ok!


Tests for write_tests.WritefileTest (0/2 passed)
--

1) write_tests.WritefileTest.test_size0_lessthanblocksize                             .. failed
.. because 'ASAN:DEADLYSIGNAL\n======================[910 chars]NG\n' != ''
Diff is 971 characters long. Set self.maxDiff to None to see it. (details below):

    Traceback (most recent call last):

      File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
        yield

      File "/usr/lib/python3.6/unittest/case.py", line 605, in run
        testMethod()

      File "/res/peters43/209/huang853/a2/test_helpers.py", line 241, in _t
        self.assertEqual(stderr, '')

      File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
        assertion_func(first, second, msg=msg)

      File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
        self.fail(self._formatMessage(msg, standardMsg))

      File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
        raise self.failureException(msg)

    AssertionError: 'ASAN:DEADLYSIGNAL\n======================[910 chars]NG\n' != ''
    Diff is 971 characters long. Set self.maxDiff to None to see it.


2) write_tests.WritefileTest.test_size2_morethanblocksize                             .. failed
.. because 'ASAN:DEADLYSIGNAL\n======================[910 chars]NG\n' != ''
Diff is 971 characters long. Set self.maxDiff to None to see it. (details below):

    Traceback (most recent call last):

      File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
        yield

      File "/usr/lib/python3.6/unittest/case.py", line 605, in run
        testMethod()

      File "/res/peters43/209/huang853/a2/test_helpers.py", line 241, in _t
        self.assertEqual(stderr, '')

      File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
        assertion_func(first, second, msg=msg)

      File "/usr/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
        self.fail(self._formatMessage(msg, standardMsg))

      File "/usr/lib/python3.6/unittest/case.py", line 670, in fail
        raise self.failureException(msg)

    AssertionError: 'ASAN:DEADLYSIGNAL\n======================[910 chars]NG\n' != ''
    Diff is 971 characters long. Set self.maxDiff to None to see it.




